apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - image: bhaskar150/vprodb:v1
          name: vprodb
          ports:
          - name:  dbport
            containerPort: 3306
            protocol: TCP
          args:
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: applicationsecrets
                  key: dbPassword
          volumeMounts:
            - name:  dbdatavolume
              mountPath: /var/lib/mysql/
      nodeSelector:
        zone: eu-north-1a
      volumes:
        - name:  dbdatavolume
          awsElasticBlockStore:
             fsType: ext4
             volumeID: vol-09c8634575f2cbbab
            
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
spec:
  selector:
    app: vprodb
  ports:
    - port: 3306
      targetPort: dbport
      protocol: TCP
  