apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprocache01
  labels:
    app: vprocache01
spec:
  selector:
    matchLabels:
      app: vprocache01
  replicas: 1
  template:
    metadata:
      labels:
        app: vprocache01
    spec:
      containers:
        - image:  memcached
          name: vprocache01
          ports:
            - name: mcport
              containerPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  selector: 
    app: vprocache01
  ports:
    - port: 11211
      targetPort: mcport
      protocol: TCP
